### ISSUE TITLE
Initial build error

### ISSUE THREAD

**Issue by anthonydillon** [Slgoetz/mlkshk-kirby-generator#1]
When following the Yeoman steps and the steps in the README. I receive this error:
`Catchable fatal error</b>:  Method Field::__toString() must return a string value in <b>/home/ant/Documents/Canonical/Kirby/mlkshk-Kirby/app/kirby/toolkit/lib/html.php</b> on line <b>105</b>`

**Comment by Slgoetz** [comment]
Are you still getting this error after the latest push?

**Comment by anthonydillon** [comment]
No I didn't, worked fine. Thank you.
